package com.example.guesstheflag

import java.util.Random

data class Question(
    val id: Int,
    val optionsArray: ArrayList<Pair<Int, String>>,
    val correctAnswer: Pair<Int, String>,

    )

object FlagRandomizer{

    val flagImages = arrayOf(
        Pair(R.drawable.ic_angola, "Angola"),
        Pair(R.drawable.ic_burundi, "Burundi"),
        Pair(R.drawable.ic_armenia, "Armenia"),
        Pair(R.drawable.ic_australia, "Australia"),
        Pair(R.drawable.ic_austria, "Austria"),
        Pair(R.drawable.ic_antigua_and_barbuda, "Antigua And Barbuda"),
        Pair(R.drawable.ic_azerbaijan, "Azerbaijan"),
        Pair(R.drawable.ic_bahamas, "Bahamas"),
        Pair(R.drawable.ic_bahrain, "Bahrain"),
        Pair(R.drawable.ic_bangladesh, "Bangladesh"),
        Pair(R.drawable.ic_barbados, "Barbados"),
        Pair(R.drawable.ic_belarus, "Belarus"),
        Pair(R.drawable.ic_belgium, "Belgium"),
        Pair(R.drawable.ic_belize, "Belize"),
        Pair(R.drawable.ic_benin, "Benin"),
        Pair(R.drawable.ic_bhutan, "Bhutan"),
        Pair(R.drawable.ic_bolivia, "Bolivia"),
        Pair(R.drawable.ic_bosnia_and_herzegovina, "Bosnia and Herzegovina"),
        Pair(R.drawable.ic_botswana, "Botswana"),
        Pair(R.drawable.ic_brazil, "Brazil"),
        Pair(R.drawable.ic_brunei, "Brunei"),
        Pair(R.drawable.ic_bulgaria, "Bulgaria"),
        Pair(R.drawable.ic_burkina_faso, "Burkina Faso"),
        Pair(R.drawable.ic_cabo_verde, "Cabo Verde"),
        Pair(R.drawable.ic_cambodia, "Cambodia"),
        Pair(R.drawable.ic_cameroon, "Cameroon"),
        Pair(R.drawable.ic_canada, "Canada"),
        Pair(R.drawable.ic_central_african_republic, "Central African Republic"),
        Pair(R.drawable.ic_chad, "Chad"),
        Pair(R.drawable.ic_chile, "Chile"),
        Pair(R.drawable.ic_china, "China"),
        Pair(R.drawable.ic_colombia, "Colombia"),
        Pair(R.drawable.ic_comoros, "Comoros"),
        Pair(R.drawable.ic_congo, "Congo"),
        Pair(R.drawable.ic_costa_rica, "Costa Rica"),
        Pair(R.drawable.ic_cote_d_ivoire, "Cote d'Ivoire"),
        Pair(R.drawable.ic_croatia, "Croatia"),
        Pair(R.drawable.ic_cuba, "Cuba"),
        Pair(R.drawable.ic_cyprus, "Cyprus"),
        Pair(R.drawable.ic_czechia, "Czechia"),
        Pair(R.drawable.ic_denmark, "Denmark"),
        Pair(R.drawable.ic_djibouti, "Djibouti"),
        Pair(R.drawable.ic_dominica, "Dominica"),
        Pair(R.drawable.ic_dominican_republic, "Dominican Republic"),
        Pair(R.drawable.ic_ecuador, "Ecuador"),
        Pair(R.drawable.ic_egypt, "Egypt"),
        Pair(R.drawable.ic_el_salvador, "EL Salvador"),
        Pair(R.drawable.ic_equatorial_guinea, "Equatorial Guinea"),
        Pair(R.drawable.ic_eritrea, "Eritrea"),
        Pair(R.drawable.ic_estonia, "Estonia"),
        Pair(R.drawable.ic_eswatini, "Eswatini"),
        Pair(R.drawable.ic_ethiopia, "Ethiopia"),
        Pair(R.drawable.ic_fiji, "Fiji"),
        Pair(R.drawable.ic_finland, "Finland"),
        Pair(R.drawable.ic_france, "France"),
        Pair(R.drawable.ic_gabon, "Gabon"),
        Pair(R.drawable.ic_gambia, "Gambia"),
        Pair(R.drawable.ic_georgia, "Georgia"),
        Pair(R.drawable.ic_germany, "Germany"),
        Pair(R.drawable.ic_ghana, "Ghana"),
        Pair(R.drawable.ic_greece, "Greece"),
        Pair(R.drawable.ic_grenada, "Grenada"),
        Pair(R.drawable.ic_guatemala, "Guatemala"),
        Pair(R.drawable.ic_guinea, "Guinea"),
        Pair(R.drawable.ic_guinea_bissau, "Guinea Bissau"),
        Pair(R.drawable.ic_guyana, "Guyana"),
        Pair(R.drawable.ic_haiti, "Haiti"),
        Pair(R.drawable.ic_honduras, "Honduras"),
        Pair(R.drawable.ic_hungary, "Hungary"),
        Pair(R.drawable.ic_iceland, "Iceland"),
        Pair(R.drawable.ic_india, "India"),
        Pair(R.drawable.ic_indonesia, "Indonesia"),
        Pair(R.drawable.ic_iran, "Iran"),
        Pair(R.drawable.ic_iraq, "Iraq"),
        Pair(R.drawable.ic_ireland, "Ireland"),
        Pair(R.drawable.ic_israel, "Israel"),
        Pair(R.drawable.ic_italy, "Italy"),
        Pair(R.drawable.ic_jamaica, "Jamaica"),
        Pair(R.drawable.ic_japan, "Japan"),
        Pair(R.drawable.ic_jordan, "Jordan"),
        Pair(R.drawable.ic_kazakhstan, "Kazakhstan"),
        Pair(R.drawable.ic_kenya, "Kenya"),
        Pair(R.drawable.ic_kiribati, "Kiribati"),
        Pair(R.drawable.ic_kosovo, "Kosovo"),
        Pair(R.drawable.ic_kuwait, "Kuwait"),
        Pair(R.drawable.ic_kyrgyzstan, "Kyrgystan"),
        Pair(R.drawable.ic_laos, "Laos"),
        Pair(R.drawable.ic_latvia, "Latvia"),
        Pair(R.drawable.ic_lebanon, "Lebanon"),
        Pair(R.drawable.ic_lesotho, "Lesotho"),
        Pair(R.drawable.ic_liberia, "Liberia"),
        Pair(R.drawable.ic_libya, "Libya"),
        Pair(R.drawable.ic_lichtenstein, "Lichtenstein"),
        Pair(R.drawable.ic_lithuania, "Lithuania"),
        Pair(R.drawable.ic_luxembourg, "Luxembourg"),
        Pair(R.drawable.ic_madagascar, "Madagascar"),
        Pair(R.drawable.ic_malawi, "Malawi"),
        Pair(R.drawable.ic_malaysia, "Malaysia"),
        Pair(R.drawable.ic_maldives, "Maldives"),
        Pair(R.drawable.ic_mali, "Mali"),
        Pair(R.drawable.ic_malta, "Malta"),
        Pair(R.drawable.ic_marshall_islands, "Marshall Islands"),
        Pair(R.drawable.ic_mauritania, "Mauritania"),
        Pair(R.drawable.ic_mauritius, "Mauritius"),
        Pair(R.drawable.ic_mexico, "Mexico"),
        Pair(R.drawable.ic_micronesia, "Micronesia"),
        Pair(R.drawable.ic_moldova, "Moldova"),
        Pair(R.drawable.ic_monaco, "Monaco"),
        Pair(R.drawable.ic_mongolia, "Mongolia"),
        Pair(R.drawable.ic_montenegro, "Montenegro"),
        Pair(R.drawable.ic_morocco, "Morocco"),
        Pair(R.drawable.ic_mozambique, "Mozambique"),
        Pair(R.drawable.ic_myanmar, "Myanmar"),
        Pair(R.drawable.ic_namibia, "Namibia"),
        Pair(R.drawable.ic_nauru, "Nauru"),
        Pair(R.drawable.ic_nepal, "Nepal"),
        Pair(R.drawable.ic_netherlands, "Netherlands"),
        Pair(R.drawable.ic_new_zealand, "New Zealand"),
        Pair(R.drawable.ic_nicaragua, "Nicaragua"),
        Pair(R.drawable.ic_niger, "Niger"),
        Pair(R.drawable.ic_nigeria, "Nigeria"),
        Pair(R.drawable.ic_north_korea, "North Korea"),
        Pair(R.drawable.ic_north_macedonia, "North Macedonia"),
        Pair(R.drawable.ic_norway, "Norway"),
        Pair(R.drawable.ic_oman, "Oman"),
        Pair(R.drawable.ic_pakistan, "Pakistan"),
        Pair(R.drawable.ic_palau, "Palau"),
        Pair(R.drawable.ic_palestine, "Palestine"),
        Pair(R.drawable.ic_panama, "Panama"),
        Pair(R.drawable.ic_papua_new_guinea, "Papua New Guinea"),
        Pair(R.drawable.ic_paraguay, "Paraguay"),
        Pair(R.drawable.ic_peru, "Peru"),
        Pair(R.drawable.ic_philippines, "Philippines"),
        Pair(R.drawable.ic_poland, "Poland"),
        Pair(R.drawable.ic_portugal, "Portugal"),
        Pair(R.drawable.ic_qatar, "Qatar"),
        Pair(R.drawable.ic_romania, "Romania"),
        Pair(R.drawable.ic_russia, "Russia"),
        Pair(R.drawable.ic_rwanda, "Rwanda"),
        Pair(R.drawable.ic_saint_vincent_and_granadines, "Saint Vincent And Grenadines"),
        Pair(R.drawable.ic_samoa, "Samoa"),
        Pair(R.drawable.ic_san_marino, "San Marino"),
        Pair(R.drawable.ic_sao_tome_and_principe, "Sao Tome And Principe"),
        Pair(R.drawable.ic_saudi_arabia, "Saudi Arabia"),
        Pair(R.drawable.ic_senegal, "Senegal"),
        Pair(R.drawable.ic_serbia, "Serbia"),
        Pair(R.drawable.ic_seychelles, "Seychelles"),
        Pair(R.drawable.ic_sierra_leone, "Sierra Leone"),
        Pair(R.drawable.ic_singapore, "Singapore"),
        Pair(R.drawable.ic_slovakia, "Slovakia"),
        Pair(R.drawable.ic_slovenia, "Slovenia"),
        Pair(R.drawable.ic_solomon_islands, "Solomon Islands"),
        Pair(R.drawable.ic_somalia, "Somalia"),
        Pair(R.drawable.ic_south_africa, "South Africa"),
        Pair(R.drawable.ic_south_korea, "South Korea"),
        Pair(R.drawable.ic_south_sudan, "South Sudan"),
        Pair(R.drawable.ic_spain, "Spain"),
        Pair(R.drawable.ic_sri_lanka, "Sri Lanka"),
        Pair(R.drawable.ic_sudan, "Sudan"),
        Pair(R.drawable.ic_suriname, "Suriname"),
        Pair(R.drawable.ic_sweden, "Sweden"),
        Pair(R.drawable.ic_switzerland, "Switzerland"),
        Pair(R.drawable.ic_syria, "Syruia"),
        Pair(R.drawable.ic_taiwan, "Taiwan"),
        Pair(R.drawable.ic_tajikistan, "Tajikistan"),
        Pair(R.drawable.ic_tanzania, "Tanzania"),
        Pair(R.drawable.ic_thailand, "Thailand"),
        Pair(R.drawable.ic_timor_leste, "Timor Leste"),
        Pair(R.drawable.ic_togo, "Togo"),
        Pair(R.drawable.ic_tonga, "Tonga"),
        Pair(R.drawable.ic_trinidad_and_tobago, "Trinidad And Tabogo"),
        Pair(R.drawable.ic_turkey, "Turkey"),
        Pair(R.drawable.ic_turkmenistan, "Turkmenistan"),
        Pair(R.drawable.ic_tuvalu, "Tuvalu"),
        Pair(R.drawable.ic_uganda, "Uganda"),
        Pair(R.drawable.ic_ukraine, "Ukraine"),
        Pair(R.drawable.ic_united_arab_emirates, "United Arab Emirates"),
        Pair(R.drawable.ic_united_kingdom, "United Kingdom"),
        Pair(R.drawable.ic_uruguay, "Uruguay"),
        Pair(R.drawable.ic_usa, "U.S.A"),
        Pair(R.drawable.ic_uzbekistan, "Uzbekistan"),
        Pair(R.drawable.ic_vanuatu, "Vanuatu"),
        Pair(R.drawable.ic_vatican_city, "Vatican City"),
        Pair(R.drawable.ic_venezuela, "Venezuela"),
        Pair(R.drawable.ic_vietnam, "Vietnam"),
        Pair(R.drawable.ic_yemen, "Yemen"),
        Pair(R.drawable.ic_zambia, "Zambia"),
        Pair(R.drawable.ic_zimbabwe, "Zimbabwe")

    )

    fun getRandomFlag(flagImg : List<Pair<Int, String>>): Pair<Int, String>{
       val randomInd = (0 until flagImg.size).random()
        return flagImg[randomInd]
    }
}